version: '3.4'

services:
  mongo-test:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27001:27017


  videoapi.web:
    image: videoapi.web:test
    build:
      dockerfile: Dockerfile
      args:
        source: ./bin/Debug/netcoreapp2.2/publish
    ports:
      - 8000:80
    links:
      - mongo-test
    working_dir: /app
    environment:
      VIDEOAPI_MONGO_USER: root
      VIDEOAPI_MONGO_PWD: admin
      VIDEOAPI_MONGO_HOST: mongo-test
      VIDEOAPI_MONGO_PORT: 27017
      VIDEOAPI_MONGO_AUTHDB: admin
      VIDEOAPI_MONGO_DB: videoapi

  #test:
  #  image: mcr.microsoft.com/dotnet/core/sdk:2.2
  #  volumes:
  #    - .:/src
  #  working_dir: /src
  #  environment:
  #    VIDEOAPI_INTEGRATION_TEST_WEB_ENDPOINT: http://localhost:8000/
  #    VIDEOAPI_MONGO_USER: root
  #    VIDEOAPI_MONGO_PWD: admin
  #    VIDEOAPI_MONGO_HOST: mongo
  #    VIDEOAPI_MONGO_PORT: 27001
  #    VIDEOAPI_MONGO_AUTHDB: admin
  #    VIDEOAPI_MONGO_DB: videoapi
  #  links:
  #    - mongo
  #    - videoapi.web
  #  command: /bin/bash -c "dotnet test ./VideoApi.IntegrationTests/VideoApi.IntegrationTests.csproj"
