version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  videoapi.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 23768:80
    links:
      - mongo
    environment:
      VIDEOAPI_MONGO_USER: root
      VIDEOAPI_MONGO_PWD: admin
      VIDEOAPI_MONGO_HOST: mongo
      VIDEOAPI_MONGO_PORT: 27017
      VIDEOAPI_MONGO_AUTHDB: admin
      VIDEOAPI_MONGO_DB: videoapi