version: '3.4'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/aspnet:2.2
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./VideoApi.sln && dotnet publish ./VideoApi.sln -c Release -o ./obj/Docker/publish"
